name: 'ğŸ•µï¸ Detect debug logging'

on:
  pull_request:

jobs:
  detection:
    name: Detect debug logging
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.ACTIONS_STEP_DEBUG == 'true' }}
        run: echo "ğŸ•µï¸"
