name: 'ğŸ•µï¸ Detect debug logging'

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    name: Detect debug logging
    runs-on: ubuntu-latest
    if: env.ACTIONS_STEP_DEBUG
    steps:
      - run: echo "ğŸ•µï¸"
